// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class HotelImage
    {
        public int HotelImageId { get; set; }
        public string HotelImagePath { get; set; }
        public int HotelId { get; set; }

        public virtual Hotel Hotel { get; set; }
    }
}