// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class HotelCatagory
    {
        public HotelCatagory()
        {
            Hotel = new HashSet<Hotel>();
        }

        public int HotelCatagoryId { get; set; }
        public string HotelCatagoryName { get; set; }

        public virtual ICollection<Hotel> Hotel { get; set; }
    }
}