// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class MemberDiscount
    {
        public int MemberId { get; set; }
        public int? DiscountId { get; set; }
        public bool? DiscountStatus { get; set; }

        public virtual Discount Discount { get; set; }
        public virtual Member Member { get; set; }
    }
}