// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class Pet
    {
        public int PetId { get; set; }
        public int? MemberId { get; set; }
        public string PetName { get; set; }
        public int? PetTypeId { get; set; }
        public string PetGender { get; set; }
        public DateTime? PetBirthday { get; set; }
        public string PetVariety { get; set; }

        public virtual Member Member { get; set; }
        public virtual PetType PetType { get; set; }
    }
}