// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class ProductImage
    {
        public int ProductImageId { get; set; }
        public string ProductImagePath { get; set; }
        public int? ProductId { get; set; }

        public virtual Product Product { get; set; }
    }
}