// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class Product
    {
        public Product()
        {
            ProductImage = new HashSet<ProductImage>();
            ProductRating = new HashSet<ProductRating>();
        }

        public int ProductId { get; set; }
        public int ProductTypeId { get; set; }
        public string ProductName { get; set; }
        public string ProductSpecification { get; set; }
        public string ProductContent { get; set; }
        public int UnitPrice { get; set; }
        public int Stock { get; set; }
        public bool ProductStatus { get; set; }
        public int ProductCatagoryId { get; set; }

        public virtual ProductCatagory ProductCatagory { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<ProductImage> ProductImage { get; set; }
        public virtual ICollection<ProductRating> ProductRating { get; set; }
    }
}