// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class SalonOrder
    {
        public SalonOrder()
        {
            SalonOrderDetail = new HashSet<SalonOrderDetail>();
        }

        public int SalonOrderId { get; set; }
        public DateTime SalonOrderDate { get; set; }
        public int MemberId { get; set; }
        public int PayId { get; set; }
        public int InvoiceId { get; set; }
        public bool OrderStatus { get; set; }
        public string OrderMemberName { get; set; }
        public string OrderMemberPhone { get; set; }
        public string OrderMemberEmail { get; set; }

        public virtual Invoice Invoice { get; set; }
        public virtual Member Member { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual ICollection<SalonOrderDetail> SalonOrderDetail { get; set; }
    }
}