// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class Salon
    {
        public Salon()
        {
            SalonSolutionSalon = new HashSet<SalonSolutionSalon>();
        }

        public int SalonId { get; set; }
        public int SalonCatagoryId { get; set; }
        public string SalonName { get; set; }
        public byte[] SalonImagePath { get; set; }

        public virtual SalonCatagory SalonCatagory { get; set; }
        public virtual ICollection<SalonSolutionSalon> SalonSolutionSalon { get; set; }
    }
}