// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class SalonOrderDetail
    {
        public int SalonOrderDetailId { get; set; }
        public DateTime Appointment { get; set; }
        public bool DetailStatus { get; set; }
        public int UnitPrice { get; set; }
        public int SalonOrderId { get; set; }
        public string SalonCatagoryName { get; set; }
        public string SalonSolutionName { get; set; }
        public int SalonSolutionId { get; set; }

        public virtual SalonOrder SalonOrder { get; set; }
    }
}