// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class SalonSolutionSalon
    {
        public int SalonSolutionSalonId { get; set; }
        public int SalonSolutionId { get; set; }
        public int SalonId { get; set; }

        public virtual Salon Salon { get; set; }
        public virtual SalonSolution SalonSolution { get; set; }
    }
}