// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class SalonCatagory
    {
        public SalonCatagory()
        {
            Salon = new HashSet<Salon>();
        }

        public int SalonCatagoryId { get; set; }
        public string SalonCatagoryName { get; set; }

        public virtual ICollection<Salon> Salon { get; set; }
    }
}