// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class SalonSolution
    {
        public SalonSolution()
        {
            SalonSolutionSalon = new HashSet<SalonSolutionSalon>();
        }

        public int SalonSolutionId { get; set; }
        public string SalonSolutionName { get; set; }
        public string SalonSolutionDiscription { get; set; }
        public int SalonSolutionPrice { get; set; }

        public virtual ICollection<SalonSolutionSalon> SalonSolutionSalon { get; set; }
    }
}