// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.PetHeavenModels
{
    public partial class ShoppingCart
    {
        public int ShoppingCartId { get; set; }
        public int? ProductId { get; set; }
        public int? Amount { get; set; }
    }
}