// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class HotelOrder
    {
        public HotelOrder()
        {
            HotelOrderDetail = new HashSet<HotelOrderDetail>();
        }

        public int HoyelOrderId { get; set; }
        public DateTime HotelOrderDate { get; set; }
        public int MemberId { get; set; }
        public int PayId { get; set; }
        public int InvoiceId { get; set; }
        public bool OrderStatus { get; set; }

        public virtual Invoice Invoice { get; set; }
        public virtual Member Member { get; set; }
        public virtual Payment Pay { get; set; }
        public virtual ICollection<HotelOrderDetail> HotelOrderDetail { get; set; }
    }
}