// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class HotelOrderDetail
    {
        public int HotelOrderDetailId { get; set; }
        public int HotelOrderId { get; set; }
        public int HotelId { get; set; }
        public DateTime CheckIntime { get; set; }
        public DateTime CheckOutTime { get; set; }
        public int OrderAmount { get; set; }
        public int UnitPrice { get; set; }
        public bool DetailStatus { get; set; }
        public string HotelName { get; set; }
        public string HotelCatagoryName { get; set; }

        public virtual HotelOrder HotelOrder { get; set; }
    }
}