// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class Hotel
    {
        public int HotelId { get; set; }
        public int HotelCatagoryId { get; set; }
        public string HotelName { get; set; }
        public int UnitPrice { get; set; }
        public string HotelContent { get; set; }
        public string HotelImage { get; set; }
        public string HotelContentDetail { get; set; }

        public virtual HotelCatogory HotelCatagory { get; set; }
    }
}