// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class Member
    {
        public Member()
        {
            HotelOrder = new HashSet<HotelOrder>();
            Pet = new HashSet<Pet>();
            ProductOrder = new HashSet<ProductOrder>();
            SalonOrder = new HashSet<SalonOrder>();
        }

        public int MemberId { get; set; }
        public string MemberAccount { get; set; }
        public string MemberPassword { get; set; }
        public string MemberGender { get; set; }
        public string MemberName { get; set; }
        public string MemberPhone { get; set; }
        public string MemberEmail { get; set; }
        public DateTime MemberBirthday { get; set; }
        public string MemberAddress { get; set; }
        public int? MemberPoint { get; set; }

        public virtual ICollection<HotelOrder> HotelOrder { get; set; }
        public virtual ICollection<Pet> Pet { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
        public virtual ICollection<SalonOrder> SalonOrder { get; set; }
    }
}