// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class Payment
    {
        public Payment()
        {
            HotelOrder = new HashSet<HotelOrder>();
            ProductOrder = new HashSet<ProductOrder>();
            SalonOrder = new HashSet<SalonOrder>();
        }

        public int PayId { get; set; }
        public string PayName { get; set; }

        public virtual ICollection<HotelOrder> HotelOrder { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
        public virtual ICollection<SalonOrder> SalonOrder { get; set; }
    }
}