// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class ProductCatagory
    {
        public ProductCatagory()
        {
            Product = new HashSet<Product>();
        }

        public int ProductCatagoryId { get; set; }
        public string ProductCatagoryName { get; set; }

        public virtual ICollection<Product> Product { get; set; }
    }
}