// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class ProductRating
    {
        public int ProductRatingId { get; set; }
        public int ProductRating1 { get; set; }
        public int ProductId { get; set; }
        public string ProductComment { get; set; }
        public string MemberName { get; set; }

        public virtual Product Product { get; set; }
    }
}