// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class SalonSolution
    {
        public int SalonSolutionId { get; set; }
        public int? SalonCatagoryId { get; set; }
        public string SalonName { get; set; }
        public string SalonDiscription { get; set; }
        public int? SalonSolutionPrice { get; set; }

        public virtual SalonCatagory SalonCatagory { get; set; }
    }
}