// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FourthTeamProject.PetHeavenModels;
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class SalonCatagory
    {
        public SalonCatagory()
        {
            SalonSolution = new HashSet<SalonSolution>();
        }

        public int SalontCatagoryId { get; set; }
        public string SalonCatagoryName { get; set; }

        public virtual ICollection<SalonSolution> SalonSolution { get; set; }
    }
}