// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class Salon
    {
        public int SalonId { get; set; }
        public string SalonName { get; set; }
        public byte[] SalonImagePath { get; set; }
    }
}