// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TEmployees
    {
        public int CEmployeeId { get; set; }
        public string CEmployeeName { get; set; }
        public int CWorkShift { get; set; }
        public int? CEmployeePhone { get; set; }
        public string CEmployeeEmail { get; set; }
        public string CEmployeeAddress { get; set; }

        public virtual TWorkShift CWorkShiftNavigation { get; set; }
    }
}