// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class THotelOrderDetail
    {
        public int COrderDetailId { get; set; }
        public int COrderId { get; set; }
        public int CService { get; set; }
        public DateTime CCheckIntime { get; set; }
        public DateTime CCheckOutTime { get; set; }
        public int COrderAmount { get; set; }
        public int CUnitPrice { get; set; }
        public bool CDetailStatus { get; set; }

        public virtual THotelOrder COrderDetail { get; set; }
        public virtual THotelService CServiceNavigation { get; set; }
    }
}