// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class THotelService
    {
        public THotelService()
        {
            THotelOrderDetail = new HashSet<THotelOrderDetail>();
        }

        public int CService { get; set; }
        public int CRoomTypeId { get; set; }
        public int CPetSizeId { get; set; }
        public int CUnitPrice { get; set; }

        public virtual TPetSize CPetSize { get; set; }
        public virtual TRoomType CServiceNavigation { get; set; }
        public virtual ICollection<THotelOrderDetail> THotelOrderDetail { get; set; }
    }
}