// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TInvoice
    {
        public TInvoice()
        {
            THotelOrder = new HashSet<THotelOrder>();
            TProductOrder = new HashSet<TProductOrder>();
        }

        public int CInvoiceId { get; set; }
        public string CInvoiceName { get; set; }

        public virtual TSalonOrder TSalonOrder { get; set; }
        public virtual ICollection<THotelOrder> THotelOrder { get; set; }
        public virtual ICollection<TProductOrder> TProductOrder { get; set; }
    }
}