// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TMemberBenefits
    {
        public int CBenefitsId { get; set; }
        public int CMemberId { get; set; }
        public int CDiscountId { get; set; }

        public virtual TDiscount CBenefits { get; set; }
        public virtual TMember CBenefitsNavigation { get; set; }
    }
}