// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TMember
    {
        public int CMemberId { get; set; }
        public string CMemberAccount { get; set; }
        public string CMemberPassword { get; set; }
        public string CMemberGender { get; set; }
        public string CMemberName { get; set; }
        public string CMemberPhone { get; set; }
        public string CMemberEmail { get; set; }
        public DateTime CMemberBirthday { get; set; }
        public string CMemberAddress { get; set; }
        public int? CMemberPoint { get; set; }
        public bool? CMemberIsActive { get; set; }

        public virtual TMemberBenefits TMemberBenefits { get; set; }
        public virtual TPet TPet { get; set; }
    }
}