// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TPayment
    {
        public TPayment()
        {
            THotelOrder = new HashSet<THotelOrder>();
            TSalonOrder = new HashSet<TSalonOrder>();
        }

        public int CPayId { get; set; }
        public string CPayName { get; set; }

        public virtual TProductOrder TProductOrder { get; set; }
        public virtual ICollection<THotelOrder> THotelOrder { get; set; }
        public virtual ICollection<TSalonOrder> TSalonOrder { get; set; }
    }
}