// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TPetSize
    {
        public TPetSize()
        {
            THotelService = new HashSet<THotelService>();
            TPet = new HashSet<TPet>();
        }

        public int CPetSizeId { get; set; }
        public string CSizeName { get; set; }

        public virtual TSalonService TSalonService { get; set; }
        public virtual ICollection<THotelService> THotelService { get; set; }
        public virtual ICollection<TPet> TPet { get; set; }
    }
}