// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TPet
    {
        public int CPetId { get; set; }
        public int CMemberId { get; set; }
        public string CPetName { get; set; }
        public int CPetSize { get; set; }
        public string CPetGender { get; set; }
        public DateTime? CPetBirthday { get; set; }
        public string CPetVariety { get; set; }

        public virtual TMember CPet { get; set; }
        public virtual TPetSize CPetSizeNavigation { get; set; }
    }
}