// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TProductType
    {
        public int CProductTypeId { get; set; }
        public string CProductTypeName { get; set; }

        public virtual TProductList CProductType { get; set; }
    }
}