// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TRoomType
    {
        public int CRoomTypeId { get; set; }
        public string CRoomTypeName { get; set; }

        public virtual THotelService THotelService { get; set; }
    }
}