// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TSalonType
    {
        public TSalonType()
        {
            TSalonService = new HashSet<TSalonService>();
        }

        public int CSalonId { get; set; }
        public string CSalonName { get; set; }
        public string CSalonContet { get; set; }

        public virtual ICollection<TSalonService> TSalonService { get; set; }
    }
}