// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TSalonOrderDetail
    {
        public int COrderDetailId { get; set; }
        public int COrderId { get; set; }
        public int CService { get; set; }
        public DateTime CAppointment { get; set; }
        public int COrderAmount { get; set; }
        public int CUnitPrice { get; set; }
        public bool CDetailStatus { get; set; }

        public virtual TSalonOrder COrderDetail { get; set; }
        public virtual TSalonService COrderDetailNavigation { get; set; }
    }
}