// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TSalonOrder
    {
        public int COrderId { get; set; }
        public DateTime COrderDate { get; set; }
        public string CMemberName { get; set; }
        public int CTotalAmount { get; set; }
        public int CPayId { get; set; }
        public int CInvoiceId { get; set; }
        public bool COrderStatus { get; set; }

        public virtual TInvoice COrder { get; set; }
        public virtual TPayment CPay { get; set; }
        public virtual TSalonOrderDetail TSalonOrderDetail { get; set; }
    }
}