// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FourthTeamProject.Models
{
    public partial class TWorkShift
    {
        public TWorkShift()
        {
            TEmployees = new HashSet<TEmployees>();
        }

        public int CShiftId { get; set; }
        public string CShiftName { get; set; }

        public virtual ICollection<TEmployees> TEmployees { get; set; }
    }
}